version: '3'
services:
  lightnode:
    build:
      context: .
      dockerfile: Light.Dockerfile
      args:
        - ETH_RPC_URL=${ETH_RPC_URL}
    env_file:
      - .env
    ports:
      - "7545:7545"
    networks:
      - etherlink_network
  etherlink:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - LIGHTNODE_RPC_URL=${LIGHTNODE_RPC_URL}
    env_file:
      - .env
    ports:
      - "26657:26657"
      - "1317:1317"
      - "4500:4500"
    networks:
      - etherlink_network
networks:
  etherlink_network:
    driver: bridge