version: '3'
services:
  etherlink:
    build:
      context: .
      dockerfile: Light.Dockerfile
      args:
        - ETH_RPC_URL=${ETH_RPC_URL}
    env_file:
      - .env
    ports:
      - "7545:7545"